version "3.7"

services:
  backend:
    container_name: nodejs
    image: hackjudge
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    restart: unless-stopped
    volumes:
      - .
    env_file: .env
    depends_on:
      -db
    networks:
      - internal
      - web
    environment:
      DATABSE_URL: "postgresql://${DB_USER}:${DB_PASS}@db/${DB_DATABASE}"
    
  db:
    container_name: db
    image: postgres:12.4
    ports:
      - 5432:5432
    env_file: .env
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      volumes:
        - ./dbdata:/var/lib/postgresql/data

  webserver:
      image: nginx:mainline-alpine
      container_name: webserver
      restart: unless-stopped
      ports:
        - "80:80"
      volumes:
        - web-root:/var/www/html
        - ./nginx-conf:/etc/nginx/conf.d
        - certbot-etc:/etc/letsencrypt
        - certbot-var:/var/lib/letsencrypt
      depends_on:
        - nodejs
      networks:
        - app-network
          
networks:
  web:
    external: true
  internal:
    external: false  
    
